openapi: 3.0.0
info:
  title: create-employee-service-api
  description: |-
    creating employee
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: dev server
tags:
  - name: create employee
    description: Operations with creating employee
paths:
  /v1/create/employee:
    post:
      summary: method to create employee
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../main/java/shop/household/request/EmployeeCreateRequest.json"
      responses:
        '200':
          description: successful answer with employee
          content:
            application/json:
              schema:
                $ref: "../../main/java/shop/household/response/ServiceResponse.json"
